# -*- coding: utf-8 -*-
"""Regenerate PROJECT_MAP.md with roles reflecting the assistant terminology
and the new skills-invocation tools."""
import os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from dev_agent import workspace_tools as wt

roles = {
    "__init__.py": "Package marker",
    "app.py": "Entry point for the platform",
    "apply_methods.py": "Method finder helper used by apply_orch_patch",
    "apply_orch_patch.py": "Patch helpers for the orchestrator UI page",
    "fix_tool_executor.py": "One-off fix helper for tool executor",
    "new_propose_desc.txt": "Draft description for propose_file tool",
    "new_propose_file.txt": "Draft full-file proposal example",
    "new_read_file.txt": "Draft read_file tool description",
    "pytest.ini": "Pytest configuration",
    "requirements.txt": "Python dependencies",
    "update_catalog.py": "Tool catalog update helper",
    "update_read_desc.py": "Read-description update helper",
    "ui/__init__.py": "Package marker",
    "ui/app.py": "Main Streamlit app: sidebar navigation and page dispatch; assistants use assistant terminology",
    "ui/components/__init__.py": "Package marker",
    "ui/components/workspace_picker.py": "Workspace picker component",
    "ui/pages/__init__.py": "Package marker",
    "ui/pages/assistants.py": "Assistants management page (create/edit/delete assistant profiles, files, tools)",
    "ui/pages/chat.py": "Chat page for AI assistants: selector, history, send form",
    "ui/pages/history.py": "Unified dialogue history page (assistants + employees)",
    "ui/pages/orchestrator.py": "Reusable orchestrator page (chat/history/settings incl. skills tab; no employee export/import UI)",
    "ui/pages/orchestrator_settings.py": "Orchestrator settings entry page",
    "ui/pages/orchestrators.py": "Employees (orchestrators) management page (create/open/settings/delete; export/import deferred)",
    "ui/pages/settings.py": "LLM provider settings page",
    "ui/pages/skills.py": "DEPRECATED shim -> ui/pages/assistants.py (page_assistants)",
    "ui/pages/skills_library.py": "Skills library page (install ZIP/GitHub/folder, edit metadata, delete)",
    "ui/pages/welcome.py": "Welcome / about page",
    "core/__init__.py": "Package marker",
    "core/api_errors.py": "API error hierarchy and user messages",
    "core/api_layer.py": "HTTP requests to AI providers; send_request(assistant=...) with legacy skill= alias",
    "core/assistant_creator.py": "Validation and linting helpers for assistant prompts",
    "core/assistants.py": "CRUD for AI assistant profiles and their attachment files",
    "core/auth.py": "Optional password authentication gate",
    "core/bootstrap.py": "First-run provisioning: Assistant/Employee Creator instructions, DevAgent settings, legacy skill_creator migration",
    "core/config.py": "Configuration load/save with secret encryption and env overlay",
    "core/contracts.py": "Typed dict contracts (AssistantDict etc.)",
    "core/crypto.py": "Encryption key handling and Fernet helpers",
    "core/dangerous.py": "Dangerous-code assessment for run_code/run_test",
    "core/env_loader.py": "Loads API keys from shell profiles",
    "core/files.py": "File upload helpers, token estimation, context checks",
    "core/fs.py": "Filesystem helpers (json/text read/write, ensure_dir, combine_nonempty)",
    "core/i18n.py": "Language discovery and translation helper t()",
    "core/instructions.py": "CRUD for internal instructions (Assistant Creator, Employee Creator)",
    "core/orchestrator_folders.py": "Per-orchestrator folders: bundles, functions, instructions",
    "core/orchestrators.py": "Orchestrator API; build_assistant_dicts (legacy alias build_skill_dicts); enabled_skills for orchestrator skills",
    "core/paths.py": "Base directories and thread paths",
    "core/prompt_guard.py": "Prompt-injection protection and sanitization",
    "core/recent_assistants.py": "Tracks recently used assistant IDs in session_state",
    "core/recent_skills.py": "DEPRECATED shim -> core/recent_assistants.py",
    "core/recent_workspaces.py": "Recent workspaces tracking",
    "core/render.py": "Markdown rendering / clipboard helpers",
    "core/services.py": "Service definitions discovery (services/*.json)",
    "core/skill_creator.py": "DEPRECATED shim -> core/assistant_creator.py",
    "core/skills.py": "DEPRECATED shim -> core/assistants.py (legacy aliases)",
    "core/skills_library.py": "Standardized skills library: registry skills.json, ZIP/GitHub/folder imports, metadata for orchestrator system prompts",
    "core/threads.py": "Chat thread persistence for assistants",
    "core/threads_devagent.py": "DevAgent/orchestrator thread persistence (devagent.db)",
    "core/tools_utils.py": "Tool definitions list for the Skills/Assistants pages",
    "tests/__init__.py": "Package marker",
    "tests/_st_mock.py": "Streamlit mock for tests",
    "tests/conftest.py": "Pytest fixture bootstrap",
    "tests/patch_api_layer.py": "Test patches for api_layer",
    "tests/patch_api_layer_v2.py": "Test patches for api_layer (v2)",
    "tests/patch_orchestrator.py": "Test patches for orchestrator",
    "tests/test_app_imports.py": "Importability tests",
    "tests/test_backup_and_safewriter.py": "Backup/safe-writer tests",
    "tests/test_core_api_layer.py": "Pure api_layer unit tests",
    "tests/test_core_api_send.py": "send_request integration tests (mocked HTTP)",
    "tests/test_core_files.py": "File helpers tests",
    "tests/test_crypto.py": "Crypto tests",
    "tests/test_deepseek_responses.py": "DeepSeek Responses API tests",
    "tests/test_devagent_thread_workspace.py": "DevAgent thread workspace persistence tests",
    "tests/test_employee_management_ui.py": "UI regression tests: employee management pages render and expose no export/import employee UI",
    "tests/test_orchestrator_folders.py": "Orchestrator folder tests",
    "tests/test_phase1_agent_loop.py": "Agent loop tests",
    "tests/test_phase1_core_pure.py": "Pure core tests",
    "tests/test_phase1_storage.py": "Storage layer tests (assistants table + legacy aliases)",
    "tests/test_platform_bootstrap.py": "Bootstrap tests",
    "tests/test_prompt_guard_strict.py": "Prompt guard strict-mode tests",
    "tests/test_propose_file.py": "propose_file tool tests",
    "tests/test_propose_file_scenarios.py": "propose_file edge-case tests",
    "tests/test_protect_history.py": "History protection tests",
    "tests/test_recent_workspaces.py": "Recent workspaces tests",
    "tests/test_render_token_line.py": "Token line renderer tests",
    "tests/test_safety_mode.py": "Safety-mode gate tests",
    "tests/test_sanitized_approval_flow.py": "Sanitized-content approval flow tests",
    "tests/test_skills_library.py": "Skills library tests",
    "tests/test_tmp_simple.py": "Temporary placeholder test",
    "tests/test_ui_pages.py": "UI page tests",
    "tests/test_universal_developer.py": "UniversalDevAgent tests",
    "tests/test_yandex_responses.py": "Yandex Responses API tests",
    "tests/smoke/test_app_smoke.py": "App smoke tests",
    "storage/__init__.py": "Package marker",
    "storage/db.py": "SQLAlchemy engines; auto-migration skills->assistants, skill_*->assistant_* columns",
    "storage/models.py": "ORM models: Assistant (assistants), Thread (assistant_id/assistant_name), Message, ConfigKV, Instruction, Orchestrator",
    "storage/repository.py": "High-level CRUD for assistants/threads/config/orchestrators + legacy repo_*_skill wrappers",
    "storage/repository_devagent.py": "DevAgent thread CRUD (devagent.db)",
    "orchestrators/autoid/instructions.json": "Test orchestrator instructions",
    "orchestrators/all_test/functions/f1.py": "Test function",
    "orchestrators/all_test/functions/f2.py": "Test function",
    "orchestrators/instr_test/instructions.json": "Test orchestrator instructions",
    "orchestrators/attached/functions/custom_tool.py": "Custom tool example",
    "orchestrators/del_test/functions/b.py": "Test function",
    "orchestrators/calc/functions/add.py": "Calculator add function example",
    "orchestrators/func_test/functions/do_thing.py": "Test function",
    "orchestrators/imported/instructions.json": "Test orchestrator instructions",
    "orchestrators/imported/orchestrator.json": "Test orchestrator bundle",
    "orchestrators/imported/functions/f1.py": "Test function",
    "orchestrators/bundle_test/orchestrator.json": "Test orchestrator bundle",
    "orchestrators/export_test/instructions.json": "Test orchestrator instructions",
    "orchestrators/export_test/orchestrator.json": "Test orchestrator bundle",
    "orchestrators/export_test/functions/f1.py": "Test function",
    "langs/en.json": "English UI strings",
    "langs/en_guide.md": "English user guide",
    "langs/ru.json": "Russian UI strings",
    "langs/ru_guide.md": "Russian user guide",
    "langs/zh-CN.json": "Simplified Chinese UI strings",
    "langs/zh_CN_guide.md": "Chinese user guide",
    "certs/russian_trusted_root_ca.pem": "Russian Trusted Root CA certificate for GigaChat TLS",
    "scripts/mig1_tool_executor.py": "Migration helper: skill->assistant in tool_executor/agent_loop",
    "scripts/mig2_fix_tool_executor.py": "Migration helper: cleanup + legacy aliases in tool_executor",
    "scripts/mig3_api_layer.py": "Migration helper: skil->assistant in api_layer",
    "scripts/mig4_repo_aliases.py": "Migration helper: repo legacy aliases",
    "scripts/mig5_orch_ui.py": "Migration helper: orchestrators/UI",
    "scripts/mig6_fix_bootstrap.py": "Migration helper: bootstrap fixes",
    "scripts/mig7_skill_tools.py": "Migration helper: add skills-library tools (list_skills_library/get_skill_folder/get_skill_prompt/get_skill_file)",
    "scripts/regenerate_project_map.py": "Regenerates PROJECT_MAP.md with assistant terminology",
    "scripts/_remove_export_import_ui.py": "One-off helper: remove employee export/import UI from orchestrator pages and language files",
    "dev_agent/README.md": "DevAgent module readme",
    "dev_agent/__init__.py": "Package marker",
    "dev_agent/agent_loop.py": "Provider-independent agent loop (strong/weak assistant routing, economy mode, skills-library tools classified as weak)",
    "dev_agent/assistant_detector.py": "Assistant detection/creation helpers (renamed from skill_detector)",
    "dev_agent/assistant_model_resolver.py": "Auto model resolution for assistant creation",
    "dev_agent/backup_manager.py": "Per-file backup/restore manager",
    "dev_agent/config.py": "DevAgent runtime config and protected path policy",
    "dev_agent/i18n_keys.json": "i18n keys placeholder",
    "dev_agent/llm_utils.py": "Unified LLM-call helper (assistant dict contract, legacy skill alias)",
    "dev_agent/safe_writer.py": "Safe full-file rewrite with diff/verification",
    "dev_agent/skill_detector.py": "DEPRECATED shim -> dev_agent/assistant_detector.py",
    "dev_agent/skill_model_resolver.py": "DEPRECATED shim -> dev_agent/assistant_model_resolver.py",
    "dev_agent/system_prompt.md": "DevAgent system prompt (assistant tool names, skills vs assistants section, skills-invocation tools)",
    "dev_agent/tool_executor.py": "DevAgent tool set; assistant tools + legacy skill tool aliases + skills-library tools",
    "dev_agent/universal_agent.py": "Universal dispatcher (core + workspace tools + orchestrator tools)",
    "dev_agent/workspace_tools.py": "Workspace layer: folders, project map, docs, snapshots",
    "services/deepseek.json": "DeepSeek service definition",
    "services/gigachat.json": "GigaChat service definition",
    "services/yandex.json": "YandexAI service definition",
}

res = wt.write_project_map(roles)
print(res)
